### ISSUE TITLE
[2020.07.01][최재영] 기존 설계 내용 정리 및 Task 설정

### ISSUE THREAD

**Issue by yoon-chaejin** [boogle-lab/ssho-daily-scrum-board#3]
# 기존 설계 내용 정리

### Server 관련 Repository
- ssho-api-document
- ssho-shopping-mall-crawling-server
- ssho-logcollector-server

### 1. ssho-api-document
- 상품(ITEM)
    - 카드덱 상품 데이터 조회
- 스와이프(SWIPE)
    - 스와이프 로그 저장
    - 스와이프 전체 조회

### 2. ssho-shopping-mall-crawling-server
- api
    - CrawlingController
    - UserController : 데이터 수집용 프로토타입에 사용
- config
    - CorsConfig
- domain
    - Item
    - User : 데이터 수집용 프로토타입에 사용
    - UserItem : 데이터 수집용 프로토타입에 사용
- model
    - ItemIdImageUrlMap
    - ProductExtra
    - Selector
    - SigninReq : 데이터 수집용 프로토타입에 사용
- repository
: domain 폴더 내 객체에 대응하는 repository interface
- service
    - impl
        - mall : 각 쇼핑몰 별 CrawlingService 구현체
        - CollectorServiceImpl
        - CommonCrawlingServiceImpl
    - (interface)CollectorService
    - (interface)CommonCrawlingService
    - (interface)CrawlingService

### 3. ssho-logcollector-server
- api
    - SwipeLogCollectorController
- config
    - CorsConfig
    - ObjectMapperConfiguration
- domain
    - Swipe
- dto
    - SwipeReq
- service
    - SwipeLogCollectorService

# Task 설정
- [ ]  코드 분석 및 응용 (Crawler 및 LogCollector)
    - [ ]  Crawling Server 주석 달기
    - [ ]  쇼핑몰(임의선택) Crawling 코드 작성
    - [ ]  LogCollector 코드 주석 달기
- [ ]  데이터 & 서버 회의 준비
    - [ ]  추천 방식 관련 조사
    - [ ]  머신러닝 서버 설계 관련 조사
    - [ ]  카테고리 계층화 관련 자료 정리
