### ISSUE TITLE
[2020-08-07] [박진영] 해커톤 클라이언트 Todo List

### ISSUE THREAD

**Issue by ed-jinyoung-park** [boogle-lab/ssho-daily-scrum-board#35]
### Tag Screen
* [ ] 레이아웃 수정 - 세로로 수평
* [ ] 검색, 완료 버튼 로직 구현 및 스타일링
* [ ] API 연결 - 태그 데이터 가져오기
* [ ] ios 작동 확인
* [ ] android 작동 확인

### Swipe Screen
* [ ] Carousel 데이터 렌더링 로직 수정 - 각 이미지 순서마다 다른 데이터
* [ ] Swiper 내 Carousel 동작 디버깅
* [x] Swiper 필요없는 로직 지우기
* [x] Swiper 스타일링
* [ ] 테스팅 & 디버깅
* [ ] ios 작동 확인
* [ ] android 작동 확인

**Swiper 메소드 동작 체크**
* [x] getCardList
* [x] setStartTime
* [x] addSwipeLog
* [x] saveSwipeLog
* [x] onSwipedLeft, Right
* [x] swipeLeft (button)
* [x] swipeRight (button)
* [ ] swipeBack
* [ ] onTapCard

**Carousel 메소드 체크**
* [ ] change
* [ ] handlePress
https://app.zeplin.io/project/5f192d5779663b6a3a7b32ba/dashboard
