### ISSUE TITLE
[2020-08-07] [최재영] 해커톤 클라이언트/서버 Todo List

### ISSUE THREAD

**Issue by yoon-chaejin** [boogle-lab/ssho-daily-scrum-board#37]
Client
- [x] 환경 설정 (에러 수정)
- [ ] API 연결 - 태그 데이터 가져오기
- [ ] Testing - iOS

Server
- [x] CSV 파일로 태그 저장
- [ ] 태그 추천 API 개발
- [ ] 태그 검색 API 개발
