### ISSUE TITLE
[2020-08-27] [박진영] 프로토타입 완성을 위한 Todo-List 정리

### ISSUE THREAD

**Issue by ed-jinyoung-park** [boogle-lab/ssho-daily-scrum-board#52]
HomeScreen
* [x] '로그인'버튼 클릭시 입력한 이름을 params로 담아 user API에 전달
* [x] 입력한 user에 따라 튜토리얼 했는지 여부 판단 - 했으면 tag스크린 , 안했으면 튜토리얼로 (swipescreen)

SwipeScreen
* [x] tutorial 용 예외처리 - item.price, item.title , extraImageList 확인
* [x] tutorial / 일반 swipe 완료 후 tagSelectScreen으로 가도록
* [ ] tutorial 로그 저장

빌드
* [ ] 안드로이드에서 우선 적용해보기

TagSelectScreen
* [x] 태그 검색 시 initial/pass 여부 확인 (안내 메시지)
* [ ] userId 로 식별하도록 수정

**Comment by ed-jinyoung-park** [comment]
@yoon-chaejin 재영님 태그화면엣 혹시 추가할 거 있으면 추가해주세요! 그리고 어제 홈화면 구현하고 이거저거 예외처리 해놓은 거 master에 merge해두었습니다.

**Comment by yoon-chaejin** [comment]
@Zinyon 추가해뒀습니다! 끝나고 알려주시면 저도 pull 받아서 테스팅 및 빌드 확인 하겠습니다!

**Comment by ywoo-park** [comment]
- Core 서비스
  - [x] 로그인 API에 튜토리얼 진행 여부 로직 추가  
  - [ ] 추천 상품 조회 API에 튜토리얼 카드덱으로 데이터 구성하는 로직 추가
     -  프론트에서 잘되는지 확인이 필요한 task
  - [x] 튜토리얼 결과 저장 API 추가
    - [ ] 한번에 7개 로그 저장하도록 변경
  - [ ] 추천 상품 조회 API에 튜토리얼 카드덱으로 데이터 구성하는 로직 추가
  - [ ] 추천 상품 캐시 저장 관련 문제 해결
  - [ ] 추천 상품 조회 API에 스와이프 횟수 100개 기준 추천 로직 분기 추가
